foreach(_required IN ITEMS GEOKERNEL_RUNTIME_DIR DESTINATION)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "${_required} was not provided.")
    endif()
endforeach()

file(MAKE_DIRECTORY "${DESTINATION}")
file(GLOB _runtime_dlls "${GEOKERNEL_RUNTIME_DIR}/*.dll")
file(GLOB _runtime_shared_libraries "${GEOKERNEL_RUNTIME_DIR}/libGeoKernel.*.so*")
foreach(_file IN LISTS _runtime_dlls)
    file(COPY "${_file}" DESTINATION "${DESTINATION}")
endforeach()
foreach(_file IN LISTS _runtime_shared_libraries)
    # Linux SDK libraries use the usual libName.so -> libName.so.X ->
    # libName.so.X.Y.Z chain. Copy both links and their real targets.
    file(COPY "${_file}" DESTINATION "${DESTINATION}" FOLLOW_SYMLINK_CHAIN)
endforeach()

foreach(_folder IN ITEMS gdal-data gdalplugins proj-data platforms tls imageformats sqldrivers)
    if(EXISTS "${GEOKERNEL_RUNTIME_DIR}/${_folder}")
        file(COPY "${GEOKERNEL_RUNTIME_DIR}/${_folder}" DESTINATION "${DESTINATION}")
    endif()
endforeach()

if(DEFINED QT_BIN_DIR AND NOT QT_BIN_DIR STREQUAL "")
    get_filename_component(_qt_root "${QT_BIN_DIR}/.." ABSOLUTE)
    foreach(_file IN LISTS QT_RUNTIME_FILES)
        if(EXISTS "${_file}")
            file(COPY "${_file}" DESTINATION "${DESTINATION}")
        endif()
    endforeach()
    foreach(_folder IN ITEMS platforms imageformats iconengines sqldrivers styles tls)
        if(EXISTS "${_qt_root}/plugins/${_folder}")
            file(COPY "${_qt_root}/plugins/${_folder}" DESTINATION "${DESTINATION}")
        endif()
    endforeach()
    if(EXISTS "${QT_BIN_DIR}/opengl32sw.dll")
        file(COPY "${QT_BIN_DIR}/opengl32sw.dll" DESTINATION "${DESTINATION}")
    endif()
endif()
